### ISSUE TITLE
theme used in image?

### ISSUE THREAD

**Issue by itsSilver** [mrchetan/phpstorm-parameter-hints-in-vscode#1]
hi man, sorry for using this as an issue but i wanted to ask what  theme are you using with the glowing $?

**Comment by mr-chetan** [comment]
> hi man, sorry for using this as an issue but i wanted to ask what  theme are you using with the glowing $?


I am using  [https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme](Material Theme).

If you want my configuration of vscode i will share with your.
