### ISSUE TITLE
Constructor property promotion

### ISSUE THREAD

**Issue by satiromarra** [mrchetan/phpstorm-parameter-hints-in-vscode#6]
The extension does not work correctly with php8, specifically with "Constructor property promotion".

```php
class MyClass
{
    public function __construct(
        public string $name, 
        public string $email, 
    ) {}
}
```

It is only necessary to update  "php-parser" package to 3.1.0-beta.10

**Comment by mr-chetan** [comment]
Check the latest version we have update
https://marketplace.visualstudio.com/items?itemName=MrChetan.phpstorm-parameter-hints-in-vscode

**Comment by mr-chetan** [comment]
![image](https://user-images.githubusercontent.com/56998650/201833515-6f6618f1-44e3-43d7-b757-6fa8e37053b7.png)
